spring.application.name=Rascomp

# H2 em memoria
spring.datasource.url=jdbc:h2:mem:rascomp
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Flyway fica desativado enquanto o projeto usa H2
spring.flyway.enabled=false
